### ISSUE TITLE
The app get stuck when the last course of its type is removed

### ISSUE THREAD

**Issue by matanelz** [ScDor/Closure#110]
**Describe the bug**
when the last(in terms of credits) course of it's type(must,choice, etc..) is removed, the app get stuck(on the analytics branch)

**To Reproduce**
1. load the app
2. add courses and remove them until the app will get stuck

**Expected behavior**
It should work properly and the progress bars should be updated

**Example**
![giphy](https://user-images.githubusercontent.com/82090448/123647572-e1028280-d830-11eb-9169-eb12ac393ce2.gif)

**Comment by matanelz** [comment]
>

**Comment by rbenjos** [comment]
thanks for notifying, ill fix that

**Comment by nmdanny** [comment]
@rbenjos I believe I already encountered and fixed this here https://github.com/ScDor/Closure/pull/107/commits/a16039545d534a587a5a8e1ecd4f8da0618f6c92

@matanelz  To verify, could you a printout of the console? (F12)

generally when something goes wrong in the front-end there are various messages printed to the console

**Comment by rbenjos** [comment]
> @rbenjos I believe I already encountered and fixed this here [a160395](https://github.com/ScDor/Closure/commit/a16039545d534a587a5a8e1ecd4f8da0618f6c92)
> 
> @matanelz To verify, could you a printout of the console? (F12)
> 
> generally when something goes wrong in the front-end there are various messages printed to the console

differerent bug i believe, anyway, fixed it
