### ISSUE TITLE
progress bars doesn't updating during courses removal

### ISSUE THREAD

**Issue by matanelz** [ScDor/Closure#113]
1. load the app(uniclosure.me)
2.remove any courses

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/82090448/123780544-f8e31080-d8db-11eb-9092-67fc9a91651b.gif)

**Comment by ScDor** [comment]
@rbenjos @nmdanny 
I suggest that we rename this issue to `Connect production FE&BE`, as afaik that's the reason. Wdyt?

**Comment by rbenjos** [comment]
allready solved in the analytics branch.
