### ISSUE TITLE
No validation on courses took in DB

### ISSUE THREAD

**Issue by ilanerukh** [ScDor/Closure#122]
**Describe the bug**
Student can take a course whenever he wants, even if the course is not present in the semester and year he chose.

**To Reproduce**
1. POST on a student with courses that he took in impossible times, like 67118 in semester A.
2. The POST is valid, and the student is saved in the database with this info.

**Expected behavior**
Validation response from the API.

**Screenshots**

**Additional context**
Could be solved in the FE side as well, but better to be solved within the API for my opinion.

**Comment by ScDor** [comment]
duplicate of #64
