### ISSUE TITLE
Problem with populating the DB from storage

### ISSUE THREAD

**Issue by ilanerukh** [ScDor/Closure#124]
**Describe the bug**
Cannot populating the DB.
Running `python manage.py migrate` ends with an error: AttributeError: module 'google' has no attribute 'exceptions'
When changing it to `google.auth.exceptions`, There is a different exception: django.db.utils.OperationalError: too many SQL variables.

**To Reproduce**
1. Run `python manage.py migrate`

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17091270/123951104-1633df80-d9ad-11eb-8a86-6da1d198bc13.png)
![image](https://user-images.githubusercontent.com/17091270/123951460-7b87d080-d9ad-11eb-808d-056d9b8e39e3.png)

**Additional context**

**Comment by ScDor** [comment]
@nmdanny @yaelmualem didn't we solve this by adding some line to the import? (haven't we merged it? 🤔)

**Comment by ilanerukh** [comment]
> @nmdanny @yaelmualem didn't we solve this by adding some line to the import? (haven't we merged it? 🤔)

Your'e talking about changing from google.exceptions to google.auth.exceptions. I tried to fix that, but encountered in a different bug after changing it.
