### ISSUE TITLE
Get course's course group, according to the track

### ISSUE THREAD

**Issue by noabarlia** [ScDor/Closure#33]
Get course's course group, according to the track via API

**Comment by ScDor** [comment]
it's done, @ilanerukh could you please create a PR so we can have it in master?

**Comment by ilanerukh** [comment]
@ScDor It's not done. We implemented it only for students that took the course. We should have the same logic for a course and a track - to respond which type the course is for the track.
Will work on it :)

**Comment by ilanerukh** [comment]
In the end, we handled this problem differently:
The course serializer calculates the course_type based on the current logged in user.

It was implemented in #87.
