### ISSUE TITLE
problem with installing the project for the first time

### ISSUE THREAD

**Issue by liatweissman** [ScDor/Closure#34]
hey,
I'm using macOS, and followed the instructions in the README file.
when I execute instruction number 2:
"run python Closure_Project/manage.py makemigrations rest_api"

i got:

"  File "Closure_Project/manage.py", line 17
    ) from execute_from_command_line(sys.argv)  "

I search this problem online and I found the next instructions:
״
Make sure which python version you connect the django with (Make sure to activate the virtual env if you are using any).

When you install django using just:
pip install django 

then you have to run:
python manage.py startapp <yourApp name>

else if you have used:
pip3 install django

then you have to run:
python3 manage.py startapp <yourapp name>
״

after I did this, the problem has still not been solved.
I also try to set  PYTHONPATH environment and make sure my virtual environment is activated.

i still get the same massege:

"  File "Closure_Project/manage.py", line 17
    ) from execute_from_command_line(sys.argv)"

I suggest that until you fix this, you open a Q&A page to the repository and add my problem with the presented solution and afterward complete it with your answer as well.
If you will accept my suggestion, I would like to later open a pull request in order to update the README file.

Liat

**Comment by ScDor** [comment]
Hi Liat, thanks for the comment.

1. Seems like you tried running the project without having the required packages installed, try running `install -r requirements.txt`.
2. Try running the commands without the `python` part (so just `manage.py` from the correct folder). 

I updated the `README` regarding these two points to prevent confusion in the future.

Please let us know if you managed to run the project, as it should run well on both Windows 10 and macOS environments.

Should you have any other comments, feel free to comment here or open a PR.

**Comment by liatweissman** [comment]
hi Dor,
thank you for your quick response 
this is still showing me the same message:
"
 python Closure_Project/manage.py makemigrations rest_api
  File "Closure_Project/manage.py", line 18
    ) from exc
         ^
SyntaxError: invalid syntax
"

I run the pip install -r requirements.txt command and tried with and without python.

any other suggestions? 
Liat

**Comment by ScDor** [comment]
The version on `master` doesn't have a syntax error, try rolling back to that version.

**Comment by DanielSaroussy** [comment]
Hi, 
I get a similar response unfortunately, and I am running the commands on Windows :(

"Traceback (most recent call last):
  File "Closure_Project/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Closure_Project/manage.py", line 22, in <module>
    main()
  File "Closure_Project/manage.py", line 17, in main
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?"

**Comment by ScDor** [comment]
Hi @DanielSaroussy, have you installed the requirements?

**Comment by ScDor** [comment]
> Hi,
> I get a similar response unfortunately, and I am running the commands on Windows :(
> 
> "Traceback (most recent call last):
> File "Closure_Project/manage.py", line 11, in main
> from django.core.management import execute_from_command_line
> ModuleNotFoundError: No module named 'django'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "Closure_Project/manage.py", line 22, in
> main()
> File "Closure_Project/manage.py", line 17, in main
> ) from exc
> ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?"

Hey, have you installed the requirements? (see updated README)

**Comment by DanielSaroussy** [comment]
> > Hi,
> > I get a similar response unfortunately, and I am running the commands on Windows :(
> > "Traceback (most recent call last):
> > File "Closure_Project/manage.py", line 11, in main
> > from django.core.management import execute_from_command_line
> > ModuleNotFoundError: No module named 'django'
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last):
> > File "Closure_Project/manage.py", line 22, in
> > main()
> > File "Closure_Project/manage.py", line 17, in main
> > ) from exc
> > ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?"
> 
> Hey, have you installed the requirements? (see updated README)

Yes I followed the updated instruction. This error happens when I run the third instruction.

**Comment by ScDor** [comment]
> > > Hi,
> > > I get a similar response unfortunately, and I am running the commands on Windows :(
> > > "Traceback (most recent call last):
> > > File "Closure_Project/manage.py", line 11, in main
> > > from django.core.management import execute_from_command_line
> > > ModuleNotFoundError: No module named 'django'
> > > The above exception was the direct cause of the following exception:
> > > Traceback (most recent call last):
> > > File "Closure_Project/manage.py", line 22, in
> > > main()
> > > File "Closure_Project/manage.py", line 17, in main
> > > ) from exc
> > > ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?"
> > 
> > 
> > Hey, have you installed the requirements? (see updated README)
> 
> Yes I followed the updated instruction. This error happens when I run the third instruction.

Please make sure the installed packages and the commands are run in the same environment
it's possible that you installed the requirements (including Django, which seems to be missing) in the virtual environment (venv) but call the commands from the windows command prompt - where Django isn't installed - can you elaborate on how exactly you installed the requirements? (windows prompt or pycharm terminal)

**Comment by DanielSaroussy** [comment]
> > > > Hi,
> > > > I get a similar response unfortunately, and I am running the commands on Windows :(
> > > > "Traceback (most recent call last):
> > > > File "Closure_Project/manage.py", line 11, in main
> > > > from django.core.management import execute_from_command_line
> > > > ModuleNotFoundError: No module named 'django'
> > > > The above exception was the direct cause of the following exception:
> > > > Traceback (most recent call last):
> > > > File "Closure_Project/manage.py", line 22, in
> > > > main()
> > > > File "Closure_Project/manage.py", line 17, in main
> > > > ) from exc
> > > > ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?"
> > > 
> > > 
> > > Hey, have you installed the requirements? (see updated README)
> > 
> > 
> > Yes I followed the updated instruction. This error happens when I run the third instruction.
> 
> Please make sure the installed packages and the commands are run in the same environment
> it's possible that you installed the requirements (including Django, which seems to be missing) in the virtual environment (venv) but call the commands from the windows command prompt - where Django isn't installed - can you elaborate on how exactly you installed the requirements? (windows prompt or pycharm terminal)

I cloned the project, than installed the requirements from windows prompt (from inside the project), then tried to run the next instruction , still from windows prompt.
![image](https://user-images.githubusercontent.com/81748842/121779431-405f6200-cba4-11eb-8120-a7f0942f6d31.png)

**Comment by ScDor** [comment]
> > > > > Hi,
> > > > > I get a similar response unfortunately, and I am running the commands on Windows :(
> > > > > "Traceback (most recent call last):
> > > > > File "Closure_Project/manage.py", line 11, in main
> > > > > from django.core.management import execute_from_command_line
> > > > > ModuleNotFoundError: No module named 'django'
> > > > > The above exception was the direct cause of the following exception:
> > > > > Traceback (most recent call last):
> > > > > File "Closure_Project/manage.py", line 22, in
> > > > > main()
> > > > > File "Closure_Project/manage.py", line 17, in main
> > > > > ) from exc
> > > > > ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?"
> > > > 
> > > > 
> > > > Hey, have you installed the requirements? (see updated README)
> > > 
> > > 
> > > Yes I followed the updated instruction. This error happens when I run the third instruction.
> > 
> > 
> > Please make sure the installed packages and the commands are run in the same environment
> > it's possible that you installed the requirements (including Django, which seems to be missing) in the virtual environment (venv) but call the commands from the windows command prompt - where Django isn't installed - can you elaborate on how exactly you installed the requirements? (windows prompt or pycharm terminal)
> 
> I cloned the project, than installed the requirements from windows prompt (from inside the project), then tried to run the next instruction , still from windows prompt.
> ![image](https://user-images.githubusercontent.com/81748842/121779431-405f6200-cba4-11eb-8120-a7f0942f6d31.png)

What do you mean `from inside the project`? Have you set up a venv? 
Anyway, try `pip freeze` to see the list of installed packages. Is Django showing?

**Comment by ScDor** [comment]
> > > > > Hi,
> > > > > I get a similar response unfortunately, and I am running the commands on Windows :(
> > > > > "Traceback (most recent call last):
> > > > > File "Closure_Project/manage.py", line 11, in main
> > > > > from django.core.management import execute_from_command_line
> > > > > ModuleNotFoundError: No module named 'django'
> > > > > The above exception was the direct cause of the following exception:
> > > > > Traceback (most recent call last):
> > > > > File "Closure_Project/manage.py", line 22, in
> > > > > main()
> > > > > File "Closure_Project/manage.py", line 17, in main
> > > > > ) from exc
> > > > > ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?"
> > > > 
> > > > 
> > > > Hey, have you installed the requirements? (see updated README)
> > > 
> > > 
> > > Yes I followed the updated instruction. This error happens when I run the third instruction.
> > 
> > 
> > Please make sure the installed packages and the commands are run in the same environment
> > it's possible that you installed the requirements (including Django, which seems to be missing) in the virtual environment (venv) but call the commands from the windows command prompt - where Django isn't installed - can you elaborate on how exactly you installed the requirements? (windows prompt or pycharm terminal)
> 
> I cloned the project, than installed the requirements from windows prompt (from inside the project), then tried to run the next instruction , still from windows prompt.
> ![image](https://user-images.githubusercontent.com/81748842/121779431-405f6200-cba4-11eb-8120-a7f0942f6d31.png)

That's odd. Could you try setting up a venv and repeating the installation & setup steps after activating it? 
If you have python2 installed (for some reason), consider using the `python3` command rather than the `python` one, and `pip3` rather than `pip`, accordingly. Let us know how it's going

**Comment by liatweissman** [comment]
> python3

how you want us to set up the venv?
pip install virtualenv?
can you please be more specific?

**Comment by ScDor** [comment]
> > python3
> 
> how you want us to set up the venv?
> pip install virtualenv?
> can you please be more specific?

Nothing special - either use PyCharm to create one, or execute `python3 -m venv venv`. (while in the project folder)

**Comment by liatweissman** [comment]
> > > python3
> > 
> > 
> > how you want us to set up the venv?
> > pip install virtualenv?
> > can you please be more specific?
> 
> Nothing special - either use PyCharm to create one, or execute `python3 -m venv venv`. (while in the project folder)

still doesn't work :(

**Comment by ScDor** [comment]
> > > > python3
> > > 
> > > 
> > > how you want us to set up the venv?
> > > pip install virtualenv?
> > > can you please be more specific?
> > 
> > 
> > Nothing special - either use PyCharm to create one, or execute `python3 -m venv venv`. (while in the project folder)
> 
> still doesn't work :(

please attach:
- the command you're running
- the output
- the output you get when calling `pip freeze`

so we can investigate it further.

**Comment by liatweissman** [comment]
> > > > > python3
> > > > 
> > > > 
> > > > how you want us to set up the venv?
> > > > pip install virtualenv?
> > > > can you please be more specific?
> > > 
> > > 
> > > Nothing special - either use PyCharm to create one, or execute `python3 -m venv venv`. (while in the project folder)
> > 
> > 
> > still doesn't work :(
> 
> please attach:
> 
> * the command you're running
> * the output
> * the output you get when calling `pip freeze`
> 
> so we can investigate it further.

I started the procedure all over again
1. I clone the repo 
and run the following commands:
2. cd /../open_source/Closure-master
3. python3 -m venv venv
4. pip install -r requirements.txt
5. python Closure_Project/manage.py makemigrations rest_api
in this stage I got the message:
"
File "Closure_Project/manage.py", line 17
    ) from exc
         ^
SyntaxError: invalid syntax
"
after running "pip freeze" this is what I get:
"
appdirs==1.4.4
asgiref==3.3.4
astroid==2.4.1
bandit==1.7.0
beautifulsoup4==4.9.3
bs4==0.0.1
certifi==2021.5.30
chardet==4.0.0
coreapi==2.3.3
coreschema==0.0.4
distlib==0.3.2
Django==3.2.4
django-cors-headers==3.6.0
django-filter==2.4.0
djangorestframework==3.12.4
docutils==0.17.1
dodgy==0.2.1
drf-yasg==1.20.0
filelock==3.0.12
flake8==3.8.4
flake8-polyfill==1.0.2
frosted==1.4.1
gitdb==4.0.7
GitPython==3.1.14
google==3.0.0
html5lib==1.1
idna==2.10
inflection==0.5.1
isort==4.3.21
itypes==1.2.0
Jinja2==3.0.1
jsonpickle==2.0.0
lazy-object-proxy==1.4.3
llist==0.7.1
lxml==4.6.3
MarkupSafe==2.0.1
mccabe==0.6.1
mypy==0.812
mypy-extensions==0.4.3
numpy==1.20.3
packaging==20.9
pandas==1.2.4
pbr==5.5.1
pep8-naming==0.10.0
pies==2.6.7
prospector==1.3.1
pycodestyle==2.6.0
pydocstyle==6.0.0
pyflakes==2.2.0
Pygments==2.8.1
pylint==2.5.3
pylint-celery==0.3
pylint-django==2.1.0
pylint-flask==0.6
pylint-plugin-utils==0.6
pyparsing==2.4.7
pyroma==3.1
python-dateutil==2.8.1
pytz==2021.1
PyYAML==5.4.1
requests==2.25.1
requirements-detector==0.7
ruamel.yaml==0.17.9
ruamel.yaml.clib==0.2.2
setoptconf==0.2.0
six==1.15.0
smmap==4.0.0
snowballstemmer==2.1.0
soupsieve==2.2.1
sqlparse==0.4.1
stevedore==3.3.0
tabulate==0.8.9
termcolor==1.1.0
toml==0.10.2
tqdm==4.60.0
typed-ast==1.4.3
typing-extensions==3.7.4.3
uritemplate==3.0.1
urllib3==1.26.5
virtualenv==20.4.7
vulture==2.3
webencodings==0.5.1
wrapt==1.12.1
"

**Comment by ScDor** [comment]
> > > > > > python3
> > > > > 
> > > > > 
> > > > > how you want us to set up the venv?
> > > > > pip install virtualenv?
> > > > > can you please be more specific?
> > > > 
> > > > 
> > > > Nothing special - either use PyCharm to create one, or execute `python3 -m venv venv`. (while in the project folder)
> > > 
> > > 
> > > still doesn't work :(
> > 
> > 
> > please attach:
> > 
> > * the command you're running
> > * the output
> > * the output you get when calling `pip freeze`
> > 
> > so we can investigate it further.
> 
> I started the procedure all over again
> 
> 1. I clone the repo
>    and run the following commands:
> 2. cd /../open_source/Closure-master
> 3. python3 -m venv venv
> 4. pip install -r requirements.txt
> 5. python Closure_Project/manage.py makemigrations rest_api
>    in this stage I got the message:
>    "
>    File "Closure_Project/manage.py", line 17
>    ) from exc
>    ^
>    SyntaxError: invalid syntax
>    "

After creating the venv, make sure you activate it. 
I'm not sure how to do that on a macOS, but Googling `activate venv mac` will probably get you there.

**Comment by liatweissman** [comment]
> > > > > > > python3
> > > > > > 
> > > > > > 
> > > > > > how you want us to set up the venv?
> > > > > > pip install virtualenv?
> > > > > > can you please be more specific?
> > > > > 
> > > > > 
> > > > > Nothing special - either use PyCharm to create one, or execute `python3 -m venv venv`. (while in the project folder)
> > > > 
> > > > 
> > > > still doesn't work :(
> > > 
> > > 
> > > please attach:
> > > 
> > > * the command you're running
> > > * the output
> > > * the output you get when calling `pip freeze`
> > > 
> > > so we can investigate it further.
> > 
> > 
> > I started the procedure all over again
> > 
> > 1. I clone the repo
> >    and run the following commands:
> > 2. cd /../open_source/Closure-master
> > 3. python3 -m venv venv
> > 4. pip install -r requirements.txt
> > 5. python Closure_Project/manage.py makemigrations rest_api
> >    in this stage I got the message:
> >    "
> >    File "Closure_Project/manage.py", line 17
> >    ) from exc
> >    ^
> >    SyntaxError: invalid syntax
> >    "
> 
> After creating the venv, make sure you activate it.
> I'm not sure how to do that on a macOS, but Googling `activate venv mac` will probably get you there.

I googled it and found the command:
source mypython/bin/activate

and now I'm getting what Daniel got:

<img width="714" alt="צילום מסך 2021-06-12 ב-18 27 51" src="https://user-images.githubusercontent.com/44327289/121781137-1447df00-cbac-11eb-8cc6-e6d0eef5ce16.png">

**Comment by ScDor** [comment]
> > > > > > > > python3
> > > > > > > 
> > > > > > > 
> > > > > > > how you want us to set up the venv?
> > > > > > > pip install virtualenv?
> > > > > > > can you please be more specific?
> > > > > > 
> > > > > > 
> > > > > > Nothing special - either use PyCharm to create one, or execute `python3 -m venv venv`. (while in the project folder)
> > > > > 
> > > > > 
> > > > > still doesn't work :(
> > > > 
> > > > 
> > > > please attach:
> > > > 
> > > > * the command you're running
> > > > * the output
> > > > * the output you get when calling `pip freeze`
> > > > 
> > > > so we can investigate it further.
> > > 
> > > 
> > > I started the procedure all over again
> > > 
> > > 1. I clone the repo
> > >    and run the following commands:
> > > 2. cd /../open_source/Closure-master
> > > 3. python3 -m venv venv
> > > 4. pip install -r requirements.txt
> > > 5. python Closure_Project/manage.py makemigrations rest_api
> > >    in this stage I got the message:
> > >    "
> > >    File "Closure_Project/manage.py", line 17
> > >    ) from exc
> > >    ^
> > >    SyntaxError: invalid syntax
> > >    "
> > 
> > 
> > After creating the venv, make sure you activate it.
> > I'm not sure how to do that on a macOS, but Googling `activate venv mac` will probably get you there.
> 
> I googled it and found the command:
> source mypython/bin/activate
> 
> and now I'm getting what Daniel got:
> 
> <img alt="צילום מסך 2021-06-12 ב-18 27 51" width="714" src="https://user-images.githubusercontent.com/44327289/121781137-1447df00-cbac-11eb-8cc6-e6d0eef5ce16.png">

have you followed the installation steps after activating the venv?

**Comment by liatweissman** [comment]
> > > > > > > > > python3
> > > > > > > > 
> > > > > > > > 
> > > > > > > > how you want us to set up the venv?
> > > > > > > > pip install virtualenv?
> > > > > > > > can you please be more specific?
> > > > > > > 
> > > > > > > 
> > > > > > > Nothing special - either use PyCharm to create one, or execute `python3 -m venv venv`. (while in the project folder)
> > > > > > 
> > > > > > 
> > > > > > still doesn't work :(
> > > > > 
> > > > > 
> > > > > please attach:
> > > > > 
> > > > > * the command you're running
> > > > > * the output
> > > > > * the output you get when calling `pip freeze`
> > > > > 
> > > > > so we can investigate it further.
> > > > 
> > > > 
> > > > I started the procedure all over again
> > > > 
> > > > 1. I clone the repo
> > > >    and run the following commands:
> > > > 2. cd /../open_source/Closure-master
> > > > 3. python3 -m venv venv
> > > > 4. pip install -r requirements.txt
> > > > 5. python Closure_Project/manage.py makemigrations rest_api
> > > >    in this stage I got the message:
> > > >    "
> > > >    File "Closure_Project/manage.py", line 17
> > > >    ) from exc
> > > >    ^
> > > >    SyntaxError: invalid syntax
> > > >    "
> > > 
> > > 
> > > After creating the venv, make sure you activate it.
> > > I'm not sure how to do that on a macOS, but Googling `activate venv mac` will probably get you there.
> > 
> > 
> > I googled it and found the command:
> > source mypython/bin/activate
> > and now I'm getting what Daniel got:
> > <img alt="צילום מסך 2021-06-12 ב-18 27 51" width="714" src="https://user-images.githubusercontent.com/44327289/121781137-1447df00-cbac-11eb-8cc6-e6d0eef5ce16.png">
> 
> have you followed the installation steps **after** activating the venv?

it worked!!!!!!!!!! 🥳🥳🥳🥳🥳🥳🥳🥳

**Comment by ScDor** [comment]
Glad to hear (:
