### ISSUE TITLE
Add progress bars

### ISSUE THREAD

**Issue by ScDor** [ScDor/Closure#49]
Add progress bars for each of the categories (`must`, `from_list`, `choice`, `supplementary`, `corner_stones`

note some tracks may not require all of the categories (for example, there may be 0 required `supplementary` points on double-major tracks), and then consider either not showing that progress bar, or show it greyed out.

**Comment by rbenjos** [comment]
added rudimentary progress bar, now need to make a method that automatically updates it

**Comment by ScDor** [comment]
Automatically as in every time the student changes their "take" objects?

**Comment by rbenjos** [comment]
added
