### ISSUE TITLE
No validation on the year of studies

### ISSUE THREAD

**Issue by yaelmualem** [ScDor/Closure#65]
It seems that there no validations for the year_in_studies parameter. We can enter a negative number which is invalid value: 
![image](https://user-images.githubusercontent.com/80756908/122982111-26433200-d3a3-11eb-9eae-c381845f56d6.png)
![image](https://user-images.githubusercontent.com/80756908/122982386-79b58000-d3a3-11eb-973d-845452ba945f.png)

**Comment by ScDor** [comment]
done in #73
