### ISSUE TITLE
Connect a domain to the deployment 

### ISSUE THREAD

**Issue by ScDor** [ScDor/Closure#66]

**Comment by nmdanny** [comment]
Apparently NameCheap(Domain provider) now participates in the Github Student Developer pack, if you connect your Github account with Namecheap you should be able to get a domain for free(haven't actually tried this yet)
https://nc.me/

**Comment by ScDor** [comment]
> Apparently NameCheap(Domain provider) now participates in the Github Student Developer pack, if you connect your Github account with Namecheap you should be able to get a domain for free(haven't actually tried this yet)
> https://nc.me/

thanks for the suggestion, but seems like HUJI isn't one of the eligable institutions. Never mind, it's just $5/yr.

We got [uniclosure.me](uniclosure.me) 🥳

**Comment by nmdanny** [comment]
> HUJI isn't one of the eligable institutions

Are they suggesting that HUJI is not good enough? Wait until Noam Nissan hears about this 😆

Anyway, URL connected, including http redirect, and ipv4+ipv6 support
