### ISSUE TITLE
Handle invalid API responses in FE

### ISSUE THREAD

**Issue by ScDor** [ScDor/Closure#79]
on #75 and #50, @yaelmualem added validations to the REST API responses. 
The FE should support them to avoid unexpected behavior.

Currently, the FE enforces that values are non-blank.
https://github.com/ScDor/Closure/blob/0230361cb9beb19b0cfcade248fd2b2f59d90356/Closure_Front_End/src/components/SearchBar.vue#L54-L60

using `.catch()` instead would be a better practice. 

Also, handle invalid responses (4xx, 5xx)

**Comment by yaelmualem** [comment]
I would handle also other status codes:
401 Unauthorized - in case that the user is unauthorized.
500 - in case there an error in the BE
